### ISSUE TITLE
Argument list not aligned with PyEsmini class

### ISSUE THREAD

**Issue by thangh** [ebadi/OpenScenarioEditor#2]
PyEsmini class seems to expect "recordFile" as argument and not "record".

Receiving this error message when trying to open a OSC-file:

_disable_ctrls = False , use_viewer =  True , threads =  True , record =  False
Traceback (most recent call last):
  File "OpenScenarioEditor.py", line 462, in openxml
    self.gui.load_file(self.xmlfn)
  File "/home/thang/OpenScenarioEditor/gui_qt.py", line 1119, in load_file
    self.reload()
  File "/home/thang/OpenScenarioEditor/gui_qt.py", line 885, in reload
    self.pyesmini = PyEsmini(
TypeError: __init__() got an unexpected keyword argument 'record'_

**Comment by ebadi** [comment]
Thanks for reporting this. I will fix this in the next version.

**Comment by omy5123** [comment]
Hello, I have the same problem. I want to use it right away, how should I modify the code?

**Comment by thangh** [comment]
The bug is fixed. Thanks @ebadi !
