### ISSUE TITLE
error No such file or directory

### ISSUE THREAD

**Issue by lsy234009** [ebadi/OpenScenarioEditor#4]
/root/OpenScenarioEditor/pyesmini/esmini/EnvironmentSimulator/Modules/Controllers/ControllerSumo.cpp:19:10: fatal error: utils/geom/PositionVector.h: No such file or directory
   19 | #include <utils/geom/PositionVector.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/root/OpenScenarioEditor/pyesmini/esmini/EnvironmentSimulator/Modules/ScenarioEngine/SourceFiles/OSIReporter.cpp:15:10: fatal error: osi_common.pb.h: No such file or directory
   15 | #include "osi_common.pb.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [EnvironmentSimulator/Modules/ScenarioEngine/CMakeFiles/ScenarioEngine.dir/build.make:183: EnvironmentSimulator/Modules/ScenarioEngine/CMakeFiles/ScenarioEngine.dir/SourceFiles/OSIReporter.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /root/OpenScenarioEditor/pyesmini/esmini/EnvironmentSimulator/Modules/ScenarioEngine/OSCTypeDefs/OSCGlobalAction.hpp:17,
                 from /root/OpenScenarioEditor/pyesmini/esmini/EnvironmentSimulator/Modules/ScenarioEngine/SourceFiles/Init.hpp:14,
                 from /root/OpenScenarioEditor/pyesmini/esmini/EnvironmentSimulator/Modules/ScenarioEngine/SourceFiles/ScenarioEngine.hpp:22,
                 from /root/OpenScenarioEditor/pyesmini/esmini/EnvironmentSimulator/Modules/ScenarioEngine/SourceFiles/IdealSensor.hpp:15,
                 from /root/OpenScenarioEditor/pyesmini/esmini/EnvironmentSimulator/Modules/ScenarioEngine/SourceFiles/IdealSensor.cpp:13:
/root/OpenScenarioEditor/pyesmini/esmini/EnvironmentSimulator/Modules/ScenarioEngine/SourceFiles/Parameters.hpp: In member function 'std::string scenarioengine::Parameters::getParameter(std::string)':

**Comment by ebadi** [comment]
Hi lsy234009,
Please remove OpenScenario directory and follow the build instruction and attach the full log from installation including the the commands that you executed and their results (and not just the outputs from running the program)

**Comment by lsy234009** [comment]
Thanks~Already fixed,change the linux version to ubuntu18
