### ISSUE TITLE
Question about WSL Environment 

### ISSUE THREAD

**Issue by kgussan** [ebadi/OpenScenarioEditor#5]
Hi, I would like to use this project, but I could not run on windows 10 WSL environment. Qt environment does not work well. 
Do you run this project on native ubuntu 20?

I think that this project is wonderful. 
Regards.

**Comment by ebadi** [comment]
Hi @kgussan,
Yes, I have only built and run this tool on Ubuntu 20.04.

**Comment by kgussan** [comment]
Hi @ebadi san,
Thank you. I will try at native ubuntu 20.04.

**Comment by ebadi** [comment]
@kgussan Hi again. You can now run the application on windows as well. A bit buggy but I am planning to fix these issues gradually if there is enough interest in the community.

**Comment by kgussan** [comment]
@ebadi san, Wow, thank you very much! It's a good news for me!
# I have tried on my PC's current Ubuntu version (16.04 and 18.04), but they did not  run.
I will try again and report here.

**Comment by kgussan** [comment]
![image](https://user-images.githubusercontent.com/2234310/121682283-dc329480-caf6-11eb-9fa2-21462ab918f6.png)
@ebadi san, I could run app on ubutu18.04 on windows 10. Thank you.!
