### ISSUE TITLE
some promblems about "git checkout....esmini 2.1.5"and "make -j4 install"

### ISSUE THREAD

**Issue by JinxBIGBIG** [ebadi/OpenScenarioEditor#6]
The orders that"git checkout....esmini 2.1.5" and make -j4 install can not work correctly

**Comment by eknabevcc** [comment]
make -j4 install I think is bound to gcc. Perhaps that's the problem?
More generic way would be:
`cmake --build . -j 4 --target install`
But the -j (parallel builds) was introduced in 3.11, so if you're running an older cmake, either update it or simply remove -j, like this:
`cmake --build . --target install`

**Comment by JinxBIGBIG** [comment]
I have tried the method introduced above ,the same error that" fatal error: utils/geom/PositionVector.h: No such file or directory
 #include <utils/geom/PositionVector.h>"  reported. Did  you have ran the OpenScenarioEditor successfully?
