### ISSUE TITLE
Couldnt run the simulation in windows

### ISSUE THREAD

**Issue by vamsi1142** [ebadi/OpenScenarioEditor#9]
When i import the scenario, when i try to press play/pause button in the Opensenario editor GUI, i am getting the following error.

  File "C:\Users\ng85756\Desktop\openscenarioeditor\OpenScenarioEditor\pyesmini\pyesmini\pyesmini.py", line 144, in __init__
    raise Exception("Init failed")

Exception: Init failed

playpause_clicked, simulatorRunning =  False
Step, simulatorRunning =  False
step_helper, simulatorRunning =  True
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Users\ng85756\Anaconda3\lib\threading.py", line 932, in _bootstrap_inner
Traceback (most recent call last):

  File "C:\Users\ng85756\Desktop\openscenarioeditor\OpenScenarioEditor\gui_qt.py", line 932, in playpause_clicked
    self.step(10000)

  File "C:\Users\ng85756\Desktop\openscenarioeditor\OpenScenarioEditor\gui_qt.py", line 924, in step
    self.update_timestamps()

  File "C:\Users\ng85756\Desktop\openscenarioeditor\OpenScenarioEditor\gui_qt.py", line 1000, in update_timestamps
    str(self.pyesmini.getSimulationTime()))

AttributeError: 'NoneType' object has no attribute 'getSimulationTime'

    self.run()
  File "C:\Users\ng85756\Anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ng85756\Desktop\openscenarioeditor\OpenScenarioEditor\gui_qt.py", line 913, in step_helper
    self.pyesmini.step()
AttributeError: 'NoneType' object has no attribute 'step'

**Comment by ebadi** [comment]
Thanks for reporting your issue. Can you please be more specific:

1- Did you follow the step for windows without any issue? 

- First install Python 3 and use pip tool to install PyQt5 (pip install pyqt5)
- Download the prebuilt binary release package and unpack it.
- Run the OpenScenarioEditor.py script: python OpenScenarioEditor.py

2- Were you able to open a scenario file as shown below? 
https://www.youtube.com/watch?v=7id7vQpcQmg

**Comment by vamsi1142** [comment]
yes. I followed every single step for windows without an issue and i opened the scenario edtior GUI to and imported the as in the vedio , but the esmini scenario player didnot open as in the vedio , so i pressed play/pause button , so there was an error that popped in my console stating this,

File "C:\Users\ng85756\Desktop\openscenarioeditor\OpenScenarioEditor\pyesmini\pyesmini\pyesmini.py", line 144, in init
raise Exception("Init failed")

Exception: Init failed

playpause_clicked, simulatorRunning = False
Step, simulatorRunning = False
step_helper, simulatorRunning = True
Exception in thread Thread-7:
Traceback (most recent call last):
File "C:\Users\ng85756\Anaconda3\lib\threading.py", line 932, in _bootstrap_inner
Traceback (most recent call last):

File "C:\Users\ng85756\Desktop\openscenarioeditor\OpenScenarioEditor\gui_qt.py", line 932, in playpause_clicked
self.step(10000)

File "C:\Users\ng85756\Desktop\openscenarioeditor\OpenScenarioEditor\gui_qt.py", line 924, in step
self.update_timestamps()

File "C:\Users\ng85756\Desktop\openscenarioeditor\OpenScenarioEditor\gui_qt.py", line 1000, in update_timestamps
str(self.pyesmini.getSimulationTime()))

AttributeError: 'NoneType' object has no attribute 'getSimulationTime'

self.run()
File "C:\Users\ng85756\Anaconda3\lib\threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "C:\Users\ng85756\Desktop\openscenarioeditor\OpenScenarioEditor\gui_qt.py", line 913, in step_helper
self.pyesmini.step()
AttributeError: 'NoneType' object has no attribute 'step'

**Comment by ebadi** [comment]
1- Did you use esmini's .xosc files in resources directory? 
2- Did you get any other error before pressing the play button?

**Comment by vamsi1142** [comment]
yes i used esmini's .xosc files in resources directory.
no i didnt get any error before pressing the play button

**Comment by ebadi** [comment]
Then I suggest you to create a video of installation and usage. Maybe I notice sth in the video.

**Comment by vamsi1142** [comment]
https://kapwi.ng/c/HuQyyGZ-p3

**Comment by ebadi** [comment]
You are using Spyder and not the terminal. My guess is that the tool cannot find the [esminiLib.dll](https://github.com/ebadi/pyesmini/blob/main/pyesmini/pyesmini.py#L107) or has an issue loading it. 
As I see, the working directory seems to be automatically adjusted (wdir) but I think it worth trying to use the terminal to load the program instead of the IDE. Otherwise I honestly have no idea what has gone wrong.

**Comment by m26raffi** [comment]
I tried the way you told me, but still it is showing the same error as before.

**Comment by vamsi1142** [comment]
Now it is working using cmd prompt, but not able to run all the scenarios that are in the esmini's .xosc files in resources directory.

**Comment by ebadi** [comment]
@vamsi1142  Great to hear that. It would be nice to share the error messages that you get when you run other esmini's .xosc files , otherwise I will close this issue.

**Comment by vamsi1142** [comment]
hello ,
when i am trying to run some .xosc files it is running but few files were not running and giving the following error message,
C:\Users\User\Desktop\open\OpenScenarioEditor>python OpenScenarioEditor.py
osc filename:  C:/Users/User/Desktop/open/esmini/esmini-2.16.0/resources/xosc/acc-test.xosc
disable_ctrls = False , use_viewer =  True , threads =  True , recordFile =
esmini GIT REV: 159852b
esmini GIT TAG: v2.9.0
esmini GIT BRANCH: tags/v2.9.0^0
esmini BUILD VERSION: 2.9.0.build.1491
Player arguments:  OpenScenarioEditor --threads --osc C:/Users/User/Desktop/open/esmini/esmini-2.16.0/resources/xosc/acc-test.xosc --window 60 60 800 400
esmini GIT REV: 159852b
esmini GIT TAG: v2.9.0
esmini GIT BRANCH: tags/v2.9.0^0
esmini BUILD VERSION: 2.9.0.build.1491
Run viewer in separate thread
Loading acc-test.xosc (v1.1)
OpenDRIVE: ../xodr/straight_500m.xodr
Scenegraph: ../models/straight_500m.osgb
Failed to resolve parameter ${$EgoSpeed / 3.6}
Failed to resolve parameter
Traceback (most recent call last):
  File "C:\Users\User\Desktop\open\OpenScenarioEditor\OpenScenarioEditor.py", line 462, in openxml
    self.gui.load_file(self.xmlfn)
  File "C:\Users\User\Desktop\open\OpenScenarioEditor\gui_qt.py", line 1123, in load_file
    self.reload()
  File "C:\Users\User\Desktop\open\OpenScenarioEditor\gui_qt.py", line 889, in reload
    self.pyesmini = PyEsmini(
  File "C:\Users\User\Desktop\open\OpenScenarioEditor\pyesmini\pyesmini\pyesmini.py", line 144, in __init__
    raise Exception("Init failed")
Exception: Init failed

**Comment by vamsi1142** [comment]
the problem is when i want to visualize the acc-test.xosc in esmini player, it is working fine. but when i try to open it with open scenario editor it is showing this error.

**Comment by eknabevcc** [comment]
Just curious, did you try with threads = False? 
threads = True will create a separate thread for the graphics, which potentially could be a source of trouble.

**Comment by vamsi1142** [comment]
To be honest , i dont know where to check ,could you tell me where i can find it

**Comment by ebadi** [comment]
@vamsi1142 
In the viewer tab:
![image](https://user-images.githubusercontent.com/1111940/142597486-a364c55e-f77d-48d7-9871-55395ccf9673.png)

**Comment by vamsi1142** [comment]
ya tried,disabling the Threads,but getting the same error.

**Comment by eknabevcc** [comment]
Sorry to hear (even though it was a long shot). I have no more clues on esmini end.

**Comment by vamsi1142** [comment]
some scenarios were ruuning ,but only few were not running so i am clueless, whats the actual problem is

**Comment by ebadi** [comment]
@vamsi1142  My best guess is that the version of esmini dll that is used for OpenScenarioEditor is not compatible with the [newer type of scenarios](https://github.com/esmini/esmini/blob/master/resources/xosc/acc-test.xosc#L46). acc-test.xosc is added to the repository recently and probably uses advanced features that is not supported by OpenScenarioEditor.
